name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  intl: ^0.20.2
  image_picker: ^1.0.4
  geolocator: ^13.0.4
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  permission_handler: ^12.0.0+1
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^6.1.3
  uuid: ^4.2.1
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add assets directory
  assets:
    - assets/images/
  
  # Fonts configuration
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
